# Generated by Django 3.1 on 2020-11-26 20:19

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations

from config.settings.base import env


def createsuperuser(apps, schema_editor):

    email = env("DJANGO_SUPERUSER_EMAIL")
    name = env("DJANGO_SUPERUSER_NAME")
    username = env("DJANGO_SUPERUSER_USERNAME")
    password = env("DJANGO_SUPERUSER_PASSWORD")

    EmailAddress = apps.get_model("account", "EmailAddress")
    User = apps.get_model("users", "User")
    Person = apps.get_model("esnpolimi_mgmt", "Person")
    ESNcard = apps.get_model("esnpolimi_mgmt", "ESNcard")
    Matricola = apps.get_model("esnpolimi_mgmt", "Matricola")
    Office = apps.get_model("esnpolimi_mgmt", "Office")

    p = Person.objects.create(name=name, email=email)

    u = User.objects.create(
        username=username,
        email=email,
        password=make_password(password),
        status="member",
        is_staff=True,
        is_superuser=True,
        person=p,
        default_office=Office.objects.get(name="Leonardo"),
    )

    EmailAddress.objects.create(user=u, email=email, primary=True, verified=True)
    ESNcard.objects.create(
        pk="PROVA1234", start_validity="2020-09-01", end_validity="2021-09-01", person=p
    )
    Matricola.objects.create(pk=899999, degree="VOID", person=p)


def reverse(apps, schema_editor):

    username = env("DJANGO_SUPERUSER_USERNAME")

    User = apps.get_model("users", "User")

    u = User.objects.get(username=username)
    p = u.person
    p.delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("esnpolimi_mgmt", "0003_createaccounts"),
    ]

    operations = [
        migrations.RunPython(createsuperuser, reverse),
    ]
