default_stages:
- commit
exclude: docs|node_modules|migrations|.git|.tox
fail_fast: true
repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 20.8b1
- hooks:
  - id: isort
  repo: https://github.com/timothycrosley/isort
  rev: 5.6.4
- hooks:
  - additional_dependencies:
    - flake8-isort
    args:
    - --config=setup.cfg
    id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.4.1
